### ISSUE TITLE
Getting subscriptions by name, type, relationship, etc. is hard

### ISSUE THREAD

**Issue by windley** [Picolab/wrangler#20] opened 2016-04-22 21:17 UTC

**Comment by burdettadam** [comment] 2016-05-03 20:37
subscriptions now takes two optional params, collection and filtered. collection is what type you would like the subscriptions collected by, filled would be the value of that type. for example,

`subscriptions()` would _return_ a list of **subscriptions**

```
{"18:floppy" :
      {"status":"inbound","relationship":"","name_space":"18",..} 
```

`subscriptions('status')` would return a collection of subscriptions

```
{ "outbound": [
      {"asdf:water-jacketing": 
         {"back_channel": "eci","status": "outbound".. } }..],
  "inbound":[.....]}
```

`subscriptions(status,outbound)` would return a collection of outbound status

```
{ "outbound": [
      {"asdf:water-jacketing": 
         {"back_channel": "1EFEFCB4-10C5-11E6-91DD-D592E71C24E1","status":    "outbound".. } }..]
```

**Comment by windley** [comment] 2016-05-03 21:51
Test, then close...

**Comment by windley** [comment] 2016-05-17 20:05
Close after writing documentation page

**Comment by burdettadam** [comment] 2016-06-06 20:30
channel takes an ID that will return a single channel. it would be nice if subscriptions provided the same api. ID should be a channel name, subscription name or the channels eci that stores the subscription information. subscriptions provided an ID should return a single subscription which corresponds with the provided ID.

**Comment by burdettadam** [comment] 2017-08-15 19:00
the method has been rewritten by 0joshuaolson1, and is much better. 
closing, because this is a possible duplicate of subscription rewrite #99 issue.

**Closed as completed** 2017-08-15 19:03 UTC
Labels: enhancement
